### PR TITLE
DEP: The implementation of Klee_abstract (no longer continued)

### PR DESCRIPTION
**Pull request by feliciahalim**
`Klee_abstract`implementation will either replace the current path condition or invoke error. If the `path condition` implies stated condition in `klee_abstract`, current path condition will be replaced by the condition in `klee_abstract`, otherwise it does not imply, the execution will terminate with abstraction error. This implementation is also part of the integration of CLP(R) with Tracer-x klee.

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim I will have a look ASAP, but for now just for planning, let us use `abstract_pr` for the works on abstraction. Therefore `abstract_pr` replaces `abstract` which has been prepared for it. I will now remove the `abstract` branch.

**Comment by feliciahalim** [comment]
@domainexpert sorry I actually planned to use `abstract_pr` as pull request for `abstract` branch, but I eventually forgot and directly use it as a pull request for master. But, it's okay if we use `abstract_pr` instead.

**Comment by domainexpert** [comment]
@feliciahalim Thank you! First, I suggest the removal of `ExecutionState::checkImplication`, as it does not use the `this` object or any of its field anyway. Instead, I suggest we completely move its implementation to `Executor::checkImplication`.

**Comment by domainexpert** [comment]
@feliciahalim I think `ExecutionState::replaceITreeConstraint` also may not really be needed as `state.itreeNode` is publicly accessible. If we moved its whole implementation to `Executor::replaceConstraint` and together with my earlier suggestion, we could leave `ExecutionState.[c,h]` completely unmodified. I think it's a good thing to leave original KLEE implementation minimally changed.

**Comment by domainexpert** [comment]
@feliciahalim For `ConstraintManager::replaceConstraint()` I think it would be better to delete the constraint with matching array (that is, `*it` satisfying `getArrayFromConcatExpr(*it) == eArray`), and then add `e` to the path condition. In this way, we could reduce the size of the path condition, which would hopefully help the solving.

**Comment by domainexpert** [comment]
@feliciahalim For `ITreeNode::replaceConstraint()`, the `condition` variable passed into the `PathCondition` constructor is of type `llvm::Value *` where it should instead have the type `VersionedValue *`.

**Comment by domainexpert** [comment]
@feliciahalim Still for `ITreeNode::replaceConstraint()`, there is a need for a construction of a new `PathCondition` linked list where only the abstraction condition + the constraints that are kept (not removed/replaced) are included. This new linked list should have no connection with the old linked list, because abstraction 'cuts off' any relationships to the parent.

**Comment by domainexpert** [comment]
@feliciahalim In `SpecialFunctionHandler::handleAbstract` there is an implication check. Here, we need to retrieve the unsatisfiability core and use it to mark the existing path condition. That is, the abstraction would not be correct without the constraints in the unsatisfiability core.

**Comment by feliciahalim** [comment]
@domainexpert  Thank you for the feedback. I am working on it. One of the feedback about : "For ITreeNode::replaceConstraint(), the condition variable passed into the PathCondition constructor is of type llvm::Value * where it should instead have the type VersionedValue *."

We don't need to change its type since path condition method itself is the one who change llvmValue * to VersionedValue *.

**Comment by domainexpert** [comment]
@feliciahalim You're right. Sorry for the mistake.

**Comment by domainexpert** [comment]
@feliciahalim I think `#include "TimingSolver.h"` can be removed from `ExecutionState.cpp`.

**Comment by domainexpert** [comment]
@feliciahalim In `SpecialFunctionHandler::handleAbstract()`, I suggest instead of `NeExpr::create(e, ...)` it may be better to use `EqExpr::create(ConstantExpr::create(0, Expr::Bool), EqExpr::create(e, ...))`. This is because `NeExpr` is non-canonical and may not be expected by some routines of KLEE.

**Comment by domainexpert** [comment]
@feliciahalim Regarding `ConstraintManager::getArrayFromConcatExpr()`, is it enough to recurse on `expr->getKid(1)` instead of to recurse on all children? Also, an expression may refer to multiple variables, so I suppose all of them must be collected by `getArrayFromConcatExpr()`.

Here basically, the abstraction condition refers to a set of variables (`Array` objects), and the constraint on the path condition (`Dependency::pathCondition` and `ExecutionState::constraints`) also may contain a set of variables. So, the task is to reason that they are intersecting, and we remove constraints on the new path condition whose variables intersect with that of the abstraction condition.

**Comment by feliciahalim** [comment]
Hi @domainexpert  Thank you very much for the feedback. I have modified it accordingly for `#include "TimingSolver.h"` and `ConstraintManager::getArrayFromConcatExpr()`. For `SpecialFunctionHandler::handleAbstract()`, I think using `NeExpr::create(e, ...)` is still find because other method such as `handleAssume` and `handlePreferCex` method have used `NeExpr::create(e, ...)`.

**Comment by domainexpert** [comment]
@feliciahalim No, thank You! I agree to leave `NeExpr::create` as is since you have found other usages in related methods.

**Comment by domainexpert** [comment]
@feliciahalim On `ConstraintManager::replaceConstraint()`, I think the types for `eArrayPack` and `itArrayPack` probably should properly be `std::set<const Array *>` instead of `std::vector<const Array *>`. There can be multiple occurrences of the same `Array` pointer in the same expression `e`, so a set should be smaller than a vector, which would simply have replicated elements in such cases.

**Comment by domainexpert** [comment]
@feliciahalim I suggest renaming `getArrayFromConcatExpr()` to just `getArrayFromExpr()` as it can be used to collect all the arrays from any `ref<Expr>`, not just `ref<ConcatExpr>`.

**Comment by domainexpert** [comment]
@feliciahalim In `ConstraintManager::replaceConstraint()`, the argument `keptConstraint` is not a reference, where it should be. This seems to be a bug because then in `Executor::replaceConstraint()` the call `state.itreeNode->replaceConstraint(..., ..., keptConstraint)` should be passed an empty vector as its last argument, which is probably not what is intended.

**Comment by domainexpert** [comment]
@feliciahalim I suggest renaming of `replaceConstraint` to `abstractConstraints` (please notice the change from singular to plural as well), and also adding of method comments for `abstractConstraints` methods.

**Comment by domainexpert** [comment]
@feliciahalim The `#ifdef SUPPORT_Z3` is no longer needed in `Executor::replaceConstraint`.

**Comment by domainexpert** [comment]
@feliciahalim Thank you! For now, would you please update the comment for `ConstraintManager::abstractConstraints` according to doxygen format? Please use `\param` and `\return` to explain the parameters and returned value. Also, there is a typo in the second line: `kept(not` should be `kept (not`.

**Comment by domainexpert** [comment]
@feliciahalim Would you please also reformat the comment of `Executor::abstractConstraints` according to doxygen format (with `\param` and `\return` to explain the parameters and return values)?

**Comment by domainexpert** [comment]
@feliciahalim I suggest renaming of `ConstraintManager::isVariableIntersect()` into `ConstraintManager::variablesIntersect()`. Here "intersect" is a verb, so "is intersect" is not grammatically correct.

**Comment by domainexpert** [comment]
@feliciahalim I think `ConstraintManager::getArrayFromExpr()` can be made static. If that is the case, then it is better to make it static, so that the compiler checks that it doesn't modify `this`.

**Comment by domainexpert** [comment]
@feliciahalim Similarly, `ConstraintManager::isVariableIntersect()` can be made static (please note that I have suggested renaming this method to `ConstraintManager::variablesIntersect()`.

**Comment by domainexpert** [comment]
@feliciahalim I suggest changing the error message for the added assertion in `SearchTree::addTableEntryMapping` to "pathCondition has no corresponding tree node" which explains more.

**Comment by domainexpert** [comment]
@feliciahalim I think `#include "klee/Solver.h"` can be removed from `ExecutionState.h`.

**Comment by domainexpert** [comment]
@feliciahalim Since `ExecutionState::constraints` is iterable and public, I believe we can move all new functionalities implemented in `ExecutionState` and `ConstraintManager` to `Executor`, mainly in `Executor::abstractConstraints()` leaving both `ExecutionState` and `ConstraintManager` unchanged. In `Executor::abstractConstraints()` we could do replace the call to `state.abstractConstraints()` with a direct implementation that iterates on `state.constraints`.

**Comment by feliciahalim** [comment]
@domainexpert  Thank you. The last feedback about move all new functionalities implemented in `ExecutionState` and `ConstraintManager`. The current structure actually follow the structure of `addConstraint`. `HandleAbstract` in the `SpecialFunctionHandler` can either addConstraint or `abstractConstraint`. I think it is okay to put the structure similar both of them for uniformity.  I also think to modular implementation is easier to debug and reused.

**Comment by feliciahalim** [comment]
@domainexpert  Removing "#include "klee/Solver.h"  from ExecutionState.h produces compile-error

**Comment by domainexpert** [comment]
Thanks for the thoughtful replies @feliciahalim . I would suggest the implementation of `Executor::checkImplication()` can be moved to `SpecialFunctionHandler::handleAbstract()`, or as a new method of `SpecialFunctionHandler`. In this way:
1. We could remove `#include "klee/Solver.h"` from `ExecutionState.h` without problem.
2. Making `ExecutionState.h` completely unmodified. I think minimal modification of KLEE classes has some value in ensuring that there will be less friction for later merging with more recent KLEE commits, which in itself has a value in that we will base Tracer-X on the best, most updated KLEE implementation.
3. `checkImplication` is one of those methods that implement a very specific functionality only useful to `SpecialFunctionHandler::handleAbstract()`. It actually can be made a static method since it does not use any field of `Executor`, hence need not be a method of `Executor`.

**Comment by domainexpert** [comment]
@feliciahalim Excellent thoughts on `ConstraintManager::abstractConstraints()` on modularity, however, in the case of `ConstraintManager::addConstraint()`, modularity has some value since it is invoked from four other methods throughout the code base, whereas in the case of `ConstraintManager::abstractConstraints()` modularity has not as much value as it is only invoked by `ExecutionState::abstractConstraints()`, and eventually only by `Executor::abstractConstraints()`. It may be more valuable to leave `ConstraintManager` and `ExecutionState` unmodified instead for the reason I have previously mentioned in this thread.

**Comment by feliciahalim** [comment]
@domainexpert Please don't merge first since I have found missed bug of assertion error in setAsCore for pathCondition has no corresponding tree node

**Comment by feliciahalim** [comment]
@domainexpert I have fixed it and now it should run for `klee-examples/abstrac`t. Please let me know what you think. Thanks.

**Comment by domainexpert** [comment]
@feliciahalim The change in semantics is based on Joxan Jaffar's verbal recommendation.

**Comment by domainexpert** [comment]
After rebasing, the example `abstract_fail.c` in `klee-examples/abstract` directory no longer works.

**Comment by domainexpert** [comment]
Need to be careful that usage of `callHistory` in `TxTreeNode::abstractConstraints` and `TxTreeNode::addConstraint` in the calls to the constructor of `PathCondition` are correct.

**Pull request closed without merging**
