### PR TITLE
mark WP vars during WPInstantiation

### PR DESCRIPTION
**Pull request by ArpitaDutta**
This PR is to solve Issue #398.

### CODE REVIEW

**Comment by ArpitaDutta** [comment]
Comparison result with master-wp is [here](https://docs.google.com/spreadsheets/d/1a-anloCQerwn84jyBOBPhbb9O_ng_ahHGOgHd_le8-c/edit?usp=sharing).

**Comment by ArpitaDutta** [comment]
Updated the [file](https://docs.google.com/spreadsheets/d/1a-anloCQerwn84jyBOBPhbb9O_ng_ahHGOgHd_le8-c/edit#gid=2077896037) with master branch deletion interpolation result.

**Comment by ArpitaDutta** [comment]
There are differences in the number of covered blocks and icmps for programs that have hit the timeout.

**Comment by rasoolmaghareh** [comment]
> There are differences in the number of covered blocks and icmps for programs that have hit the timeout.

I checked the results, we need to investigate why this program is reaching timeout: `Wtest32-B15`

**Comment by ArpitaDutta** [comment]
I have checked both the result files and this program is reaching timeout for all the branches.

**Review by rasoolmaghareh — APPROVED** [review]

**Review by rasoolmaghareh — APPROVED** [review]

**Review by sanghu1790 — APPROVED** [review]

**Pull request merged**
