### PR TITLE
DEP: The implementation of Fourier Motzkin Elimination algorithm (no longer continued)

### PR DESCRIPTION
**Pull request by feliciahalim**
Hi Andrew, I have pushed the implementation of Fourier Motzkin Elimination algorithm. It currently able to make subsumption for all addition_safe example in https://github.com/feliciahalim/klee-examples/tree/master/basic . 

However, there are still limitations in the current version such as it works only for addition and subtraction operation. This version also has not handle strict inequality. I will continue to work on it by enable more operation and also handling strict inequality.

### CODE REVIEW

**Comment by domainexpert** [comment]
@feliciahalim I think it would be nice to have constant multiplication and division as as well (e.g., computing the coefficients of (3 x + 2 y) 4 by converting it to 12 x + 8 y. However, when multiplication results in nonlinear expression, e.g., (3x + 2y) x, which is 3 x^2 + 2yx we should remove the constraint containing the expression from consideration. 

For strict inequalities, the way they are handled is as follows:

Given x <= expr1 and expr2 <= x, we eliminate x with introducing the constraint expr2 <= expr1.
Given x <= expr1 and expr2 < x, we eliminate x with introducing the constraint expr2 < expr1.
Given x < expr1 and expr2 <= x, we eliminate x with introducing the constraint expr2 < expr1.
Given x < expr1 and expr2 < x, we eliminate x with introducing the constraint expr2 < expr1.

**Comment by feliciahalim** [comment]
@domainexpert I have pushed the implementation of handling more operations such as constant multiplication and division. It is also handling strict inequality. Details in here: https://github.com/feliciahalim/klee/pull/43/commits/7f883530f4fd28fcb1d6beebb0a1d3a9004a88d6

**Comment by domainexpert** [comment]
@feliciahalim The algorithm now can run all basic examples. In https://github.com/tracer-x/klee-examples/commit/8342275000934ae6039fc131f163939352c5339b resulted in 4 subsumptions with `basic/addition_safe4.c` instead of 2 for the master branch, also 35 subsumptions for `basic/regexp_nonrecursive2.c`.  However, the implementation causes significant slowdown for `scalability/Regexp.c`, where it didn't terminate in 8 minutes, whereas master terminates on the same example in just 211 seconds.

**Comment by domainexpert** [comment]
@feliciahalim @nguyenquocbinh A rethinking of the data structures may be needed, but we need to first profile the execution of the Fourier-Motzkin simplifier.

**Comment by domainexpert** [comment]
@feliciahalim @nguyenquocbinh I've just rearranged to code for readability. Please note that we still get the same error reports as master branch.

**Comment by feliciahalim** [comment]
@domainexpert  Thank you for the implementation and testing. This PR actually were branched from master about a month ago. So, I am afraid some new commits from the master branch is not available here that might affect the result.
In addition, the simplification occurs 2 times : simplified with the previous method (simple substitution) and then with Fourier Motzkin. In case of Regexp.c test case, there's actually many expressions that only need the first pass of simplification that makes the solver strong enough to solve it. So, I thought of treating Fourier Motzkin as an additional simplification which only occur if the first simplification failed to simplify the expression. 
I implemented the idea in here: https://github.com/tracer-x/klee/tree/newfourier
I executed Regexp.c in this branch and it able to terminates around 3.5 minutes with 234 subsumed paths.
Please let me know your opinion about this. Thank you.

**Comment by domainexpert** [comment]
@feliciahalim Firstly, I've merged the development branch to the latest version of master, so the `development` branch is not a stale version afaik. I have diff-ed `newfourier` and `development` and they are basically the same, but the most important differences are in the addition of timer for Fourier-Motzkin simplification, which seems unused, and the new simplification strategy that you implemented. I think it's an awesome idea. However, there are several things in `newfourier` that I would be hesitant to merge, such as the removal of `const` specifier from `PathCondition::print` and `ITree::printTableStat` method and the use of `llvm::isa ... || llvm::isa ...` long condition instead of just `isVariable`.

Would you please implement the idea in the `development` branch, which are the following two modifications:
```
@@ -1034,7 +1034,10 @@ SubsumptionTableEntry::simplifyArithmeticBody(ref<Expr> existsExpr,
     newBody = AndExpr::alloc(simplifiedInterpolant, fullEqualityConstraint);
   }
 
-  return FourierMotzkin::simplify(existsExpr->rebuild(&newBody));
+  // simplifywithFourierTimer.start();
+  //ref<Expr> temp = FourierMotzkin::simplify(existsExpr->rebuild(&newBody));
+  //simplifywithFourierTimer.stop();
+  return existsExpr->rebuild(&newBody);
 }
```
and
```
@@ -1360,10 +1365,12 @@ bool SubsumptionTableEntry::subsumed(TimingSolver *solver,
 
   if (!existentials.empty()) {
     ref<Expr> existsExpr = ExistsExpr::create(existentials, query);
-    //     llvm::errs() << "Before simplification:\n";
-    //     ExprPPrinter::printQuery(llvm::errs(), state.constraints,
-    // existsExpr);
+    // llvm::errs() << "Before simplification:\n";
+    // ExprPPrinter::printQuery(llvm::errs(), state.constraints, existsExpr);
     query = simplifyExistsExpr(existsExpr, queryHasNoFreeVariables);
+    if(query.operator ==(existsExpr)){
+       query =  FourierMotzkin::simplify(query);
+    }
   }
```
If you want, you can also add the timing for FourierMotzkin::simplify method invocation, which I kind of like as well.

**Comment by domainexpert** [comment]
@feliciahalim An alternative way to do it is to improve the simplification algorithm. Given n the number of variables considered, including existentials and universals and m the number of inequalities, the current algorithm performs O(m . n^2) steps at each matching iteration, as the normalization procedure is O(n^2). I think the use of matrix instead of lists of vectors would reduce this to just O(m . n).

**Comment by domainexpert** [comment]
@feliciahalim Correction: The normalization procedure is O(n . log n). Still, replacing it with O(n) procedure would be good. When matrices are used, no normalization needs to be done at each step, and matching is done in O(n) steps. Here, the columns are for the variables used in each term, and the rows are for the inequalities. The matching procedure is done by traversing the terms in two matching inequalities in the same order, while subtracting the coefficients of the corresponding terms with the same variables in both inequalities.

**Comment by domainexpert** [comment]
@feliciahalim I think we should record here what happened to `newfourier` branch. Two days ago I recommended the integration of the optimizations in `newfourier` branch into `development` branch, where the main development of the Fourier-Motzkin elimination is happening. The recommended modifications were as follows:
```
@@ -1034,7 +1034,10 @@ SubsumptionTableEntry::simplifyArithmeticBody(ref<Expr> existsExpr,
     newBody = AndExpr::alloc(simplifiedInterpolant, fullEqualityConstraint);
   }

-  return FourierMotzkin::simplify(existsExpr->rebuild(&newBody));
+  // simplifywithFourierTimer.start();
+  //ref<Expr> temp = FourierMotzkin::simplify(existsExpr->rebuild(&newBody));
+  //simplifywithFourierTimer.stop();
+  return existsExpr->rebuild(&newBody);
 }
```
and
```
@@ -1360,10 +1365,12 @@ bool SubsumptionTableEntry::subsumed(TimingSolver *solver,

   if (!existentials.empty()) {
     ref<Expr> existsExpr = ExistsExpr::create(existentials, query);
-    //     llvm::errs() << "Before simplification:\n";
-    //     ExprPPrinter::printQuery(llvm::errs(), state.constraints,
-    // existsExpr);
+    // llvm::errs() << "Before simplification:\n";
+    // ExprPPrinter::printQuery(llvm::errs(), state.constraints, existsExpr);
     query = simplifyExistsExpr(existsExpr, queryHasNoFreeVariables);
+    if(query.operator ==(existsExpr)){
+       query =  FourierMotzkin::simplify(query);
+    }
   }
```
 It seems what happened was that we lost the extra subsumptions for `basic/addition_safe8.c` and `basic/regexp_norecursive2.c`. However, it is also bad to not remove the `newfourier` branch, as such branches, which have something that may be valuable, when left as is, will be harder and harder to manage. 
1. So I believe the best thing to do in this situation is to merge `newfourier` into `development`, but 
    comment out its modifications with explanations.
2. Delete the `newfourier` branch.

@feliciahalim Please tell what you think.

**Comment by domainexpert** [comment]
@feliciahalim I am happy to work on this.

**Comment by feliciahalim** [comment]
@domainexpert I have merged newfourier to this PR in my local. In my local version, I actually did not commented the implementation as you mentioned in the number 1 because it is not decreasing the number of subsumption/ error rate for `basic`, `regexp`, and `tr`. The reason why we did not lose the subsumption especially in `addition_safe8` because we already merged with PR   https://github.com/tracer-x/klee/pull/69 .
Moreover for `tr_nosyscall` the subsumption is increasing into 2 instead of 1, and for `tr_small` the subsumption is also increasing into 9 instead of 3, and error rates become 5 instead of  1. 
This updates also doesn't slow down the performance. 
So, should I merge the commented or uncommented version? Thanks.

**Comment by domainexpert** [comment]
@feliciahalim Thank you! What are the subsumption numbers for `addition_safe8.c` and `regexp_nonrecursive2.c` in the uncommented version? I remember we have 4 and 35 in the development branch.

I think for `tr_nosyscall` the result is probably subject to nondeterminism, so let us not consider it for now. For `tr_small`, are the result consistent across multiple runs, and what is the difference in the number of instructions in commented/uncommented versions? Does 5 error rates mean 5 different errors reported or does it mean 5 error paths?

**Comment by feliciahalim** [comment]
@domainexpert Sorry I think I falsely compare the result between uncommented to master branch instead of commented version. 
For Regexp, It is true that we lose subsumptions from 35 to 32. But, the number of subsumptions for `addition_safe8` is still 4 for both commented and uncommented.

I also need to revised `tr_small` result because It seems there's no difference between uncommented and commented version. There are 9 subsumed paths, 5 error paths, and 23085 total instructions.
`Tr_small` also subject to nondeterminism because the instructions can be 23113 and subsumed paths can be 8.

**Comment by domainexpert** [comment]
@feliciahalim Thank you again, but I think for now it may not be worth putting more work on this branch unless we change the core algorithm to replace the O(n . log n) normalization (call to `Inequality::normalize`) with O(n) matrix row addition. I recommend to push your commits to this branch with the `newfourier` modifications commented out with sufficient explanation, except for the timer for the profiling of `FourierMotzkin::simplify`.

**Comment by feliciahalim** [comment]
@domainexpert I have pushed commits to this branch with the `newfourier` modifications commented out with explanation. `newfourier` is already deleted.

**Comment by domainexpert** [comment]
@feliciahalim Excellent! I've pushed a commit just to make the comments a little bit more elaborate. Thank you!

**Pull request closed without merging**
