### PR TITLE
fix in txExpr2z3Expr

### PR DESCRIPTION
**Pull request by ArpitaDutta**

### CODE REVIEW

**Comment by rasoolmaghareh** [comment]
We are planning to test this PR on our test programs. @ArpitaDutta please report the test results here. Thanks

**Comment by ArpitaDutta** [comment]
I have done my testing of this PR on Smoke-test programs for both the master branch and new-wpinterpolant branch.
Only for the program m34CTLAI-B3.c, this PR is unable to finish and reported the following error.
-----------------------------------------------
Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see
/etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No symbol table is loaded.  Use the "file" command.
The program is not being run.
KLEE: WARNING: KLEE: WATCHDOG: kill(9)ing child (I tried to be nice)
---------------------------------------------------------------

**Comment by ArpitaDutta** [comment]
I have done testing of this PR on half of the programs from TracerX/tree/master/test/Smoke_Test using both the master branch and new-wpinterpolant branch (by making the required changes for new-wp).

Everything seems fine except for one program m34CTLAI-B3.c.
For this program, the following error is obtained.

`Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see
/etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No symbol table is loaded.  Use the "file" command.
The program is not being run.
KLEE: WARNING: KLEE: WATCHDOG: kill(9)ing child (I tried to be nice)`

**Comment by rasoolmaghareh** [comment]
@ArpitaDutta can you please post the outputs for the `m34CTLAI-B3.c.` program here? Thanks

**Comment by ArpitaDutta** [comment]
Hi @rasoolmaghareh, 
Below is the output for `m34CTLAI-B3.c`. program.
```

Using Z3 solver backend
KLEE: WARNING: undefined reference to function: printf
KLEE: WARNING ONCE: calling external: printf(61476776)
KLEE: WARNING: KLEE: WATCHDOG: time expired, attempting halt via INT

KLEE: ctrl-c detected, requesting interpreter to halt.
KLEE: WARNING: KLEE: WATCHDOG: time expired, attempting halt via gdb

Could not attach to process.  If your uid matches the uid of the target
process, check the setting of /proc/sys/kernel/yama/ptrace_scope, or try
again as the root user.  For more details, see /etc/sysctl.d/10-ptrace.conf
ptrace: Operation not permitted.
No symbol table is loaded.  Use the "file" command.
The program is not being run.
KLEE: WARNING: KLEE: WATCHDOG: kill(9)ing child (I tried to be nice)

---------------------------------------------------------------------------------------
|          Path          |  Instrs|  Time(s)|  ICov(%)|  BCov(%)|  ICount|  TSolver(%)|
---------------------------------------------------------------------------------------
|m34CTLAI-B3-3/klee-out-0|    8944|     6.62|     5.22|     4.80|   26329|        0.42|
---------------------------------------------------------------------------------------
```

**Comment by alvin21mfmlai** [comment]
**Master-Branch (no modifications to Z3Simplification.cpp & with deletion)**								
image

**Master-Branch (modifications to Z3Simplification.cpp & with deletion)**								
image

**Persistent Memory-Branch (no modifications to Z3Simplification.cpp & with wp interpolant)**	
image

**Persistent Memory-Branch (modifications to Z3Simplification.cpp & with wp interpolant)**	
image

**Master-Branch (no modifications to Z3Simplification.cpp & with wp interpolant)**	
image

**Master-Branch (modifications to Z3Simplification.cpp & with wp interpolant)**	
image

**Pull request closed without merging**
